# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientMetrics.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ClientMetrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43lientMetrics.proto\x12\x1e\x63om.ea.simpsons.client.metrics\"\xa0\x01\n\x14\x43lientMetricsMessage\x12G\n\x04type\x18\x01 \x01(\x0e\x32\x39.com.ea.simpsons.client.metrics.ClientMetricsMessage.Type\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x03\"\"\n\x04Type\x12\x0b\n\x07\x43OUNTER\x10\x00\x12\r\n\tHISTOGRAM\x10\x01\x42%\n\x14\x63om.ea.simpsons.dataB\rClientMetricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientMetrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.ea.simpsons.dataB\rClientMetrics'
  _globals['_CLIENTMETRICSMESSAGE']._serialized_start=56
  _globals['_CLIENTMETRICSMESSAGE']._serialized_end=216
  _globals['_CLIENTMETRICSMESSAGE_TYPE']._serialized_start=182
  _globals['_CLIENTMETRICSMESSAGE_TYPE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
