# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AuthData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'AuthData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Error_pb2 as Error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x41uthData.proto\x12\x04\x44\x61ta\x1a\x0b\x45rror.proto\"\\\n\x10UserIndirectData\x12\x13\n\x06userId\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0btelemetryId\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_userIdB\x0e\n\x0c_telemetryId\"=\n\x11\x41nonymousUserData\x12\x18\n\x0bisAnonymous\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x0e\n\x0c_isAnonymous\"c\n\tTokenData\x12\x17\n\nsessionKey\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0e\x65xpirationDate\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\r\n\x0b_sessionKeyB\x11\n\x0f_expirationDate\"y\n\x14UsersResponseMessage\x12)\n\x04user\x18\x01 \x01(\x0b\x32\x16.Data.UserIndirectDataH\x00\x88\x01\x01\x12#\n\x05token\x18\x02 \x01(\x0b\x32\x0f.Data.TokenDataH\x01\x88\x01\x01\x42\x07\n\x05_userB\x08\n\x06_token\"\x9f\x02\n\x08LinkData\x12\x34\n\nsourceType\x18\x01 \x01(\x0e\x32\x1b.Data.LinkData.identityTypeH\x00\x88\x01\x01\x12\x15\n\x08sourceId\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x39\n\x0f\x64\x65stinationType\x18\x03 \x01(\x0e\x32\x1b.Data.LinkData.identityTypeH\x02\x88\x01\x01\x12\x1a\n\rdestinationId\x18\x04 \x01(\tH\x03\x88\x01\x01\"-\n\x0cidentityType\x12\n\n\x06TNT_ID\x10\x00\x12\x11\n\rNUCLEUS_TOKEN\x10\x01\x42\r\n\x0b_sourceTypeB\x0b\n\t_sourceIdB\x12\n\x10_destinationTypeB\x10\n\x0e_destinationId\"\xbf\x01\n\x17LinkUserResponseMessage\x12\x13\n\x06userId\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nexternalId\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0c\x65xternalType\x18\x03 \x01(\tH\x02\x88\x01\x01\x12&\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x12.Data.ErrorMessageH\x03\x88\x01\x01\x42\t\n\x07_userIdB\r\n\x0b_externalIdB\x0f\n\r_externalTypeB\x08\n\x06_error\"m\n\x19\x44\x65leteUserResponseMessage\x12\x13\n\x06userId\x18\x01 \x01(\tH\x00\x88\x01\x01\x12&\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.Data.ErrorMessageH\x01\x88\x01\x01\x42\t\n\x07_userIdB\x08\n\x06_errorB!\n\x1f\x63om.eamobile.mayhem.plugin.datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AuthData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.eamobile.mayhem.plugin.data'
  _globals['_USERINDIRECTDATA']._serialized_start=37
  _globals['_USERINDIRECTDATA']._serialized_end=129
  _globals['_ANONYMOUSUSERDATA']._serialized_start=131
  _globals['_ANONYMOUSUSERDATA']._serialized_end=192
  _globals['_TOKENDATA']._serialized_start=194
  _globals['_TOKENDATA']._serialized_end=293
  _globals['_USERSRESPONSEMESSAGE']._serialized_start=295
  _globals['_USERSRESPONSEMESSAGE']._serialized_end=416
  _globals['_LINKDATA']._serialized_start=419
  _globals['_LINKDATA']._serialized_end=706
  _globals['_LINKDATA_IDENTITYTYPE']._serialized_start=595
  _globals['_LINKDATA_IDENTITYTYPE']._serialized_end=640
  _globals['_LINKUSERRESPONSEMESSAGE']._serialized_start=709
  _globals['_LINKUSERRESPONSEMESSAGE']._serialized_end=900
  _globals['_DELETEUSERRESPONSEMESSAGE']._serialized_start=902
  _globals['_DELETEUSERRESPONSEMESSAGE']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
