# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Error.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'Error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x45rror.proto\x12\x04\x44\x61ta\"\xae\x07\n\x0c\x45rrorMessage\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x17.Data.ErrorMessage.Code\x12%\n\x04type\x18\x02 \x01(\x0e\x32\x17.Data.ErrorMessage.Type\x12\r\n\x05\x66ield\x18\x03 \x01(\t\x12-\n\x08severity\x18\x04 \x01(\x0e\x32\x1b.Data.ErrorMessage.Severity\x12\x0f\n\x07message\x18\x05 \x01(\t\"\xc9\x01\n\x04\x43ode\x12\x10\n\x0cUNKNOWN_CODE\x10\x01\x12\x11\n\x0cUNAUTHORIZED\x10\x91\x03\x12\x0e\n\tNOT_FOUND\x10\x94\x03\x12\r\n\x08\x43ONFLICT\x10\x99\x03\x12\x1a\n\x15INTERNAL_SERVER_ERROR\x10\xf4\x03\x12\x14\n\x0fNOT_IMPLEMENTED\x10\xf5\x03\x12\x18\n\x13SERVICE_UNAVAILABLE\x10\xf7\x03\x12\x1f\n\x1aHTTP_VERSION_NOT_SUPPORTED\x10\xf9\x03\x12\x10\n\x0b\x42\x41\x44_REQUEST\x10\x90\x03\"\xd5\x03\n\x04Type\x12\x11\n\rUNKNOWN_ERROR\x10\x01\x12\x18\n\x14\x41UTHENTICATION_ERROR\x10\x02\x12\x12\n\x0eNO_SUCH_METHOD\x10\x03\x12\x14\n\x10NO_SUCH_RESOURCE\x10\x04\x12\x11\n\rMISSING_VALUE\x10\x05\x12\x11\n\rINVALID_VALUE\x10\x06\x12\x13\n\x0fVALUE_TOO_SMALL\x10\x07\x12\x13\n\x0fVALUE_TOO_LARGE\x10\x08\x12\x1b\n\x17RESOURCE_ALREADY_EXISTS\x10\t\x12\x1b\n\x17METHOD_CALLED_TOO_OFTEN\x10\x17\x12\x1d\n\x19INVALID_PARAMETERS_FORMAT\x10\x18\x12&\n\"LOCK_REQUEST_FAILED_DUE_TO_TIMEOUT\x10\x1a\x12\x15\n\x11PROTOCOL_MISMATCH\x10\x1c\x12\x12\n\x0e\x44\x41TABASE_ERROR\x10\x1d\x12\x1c\n\x18SERVICE_UNAVAILABLE_TYPE\x10\x1e\x12\x18\n\x14NOT_IMPLEMENTED_TYPE\x10\x1f\x12\x10\n\x0cSERVER_ERROR\x10 \x12\x1b\n\x17SHARD_UNDER_MAINTENANCE\x10\"\x12\x13\n\x0fPLUGIN_INACTIVE\x10#\"]\n\x08Severity\x12\x0f\n\x0bLEVEL_DEBUG\x10\x00\x12\x0e\n\nLEVEL_INFO\x10\x01\x12\x0e\n\nLEVEL_WARN\x10\x02\x12\x0f\n\x0bLEVEL_ERROR\x10\x03\x12\x0f\n\x0bLEVEL_FATAL\x10\x04\x42\x16\n\x14\x63om.ea.simpsons.data')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.ea.simpsons.data'
  _globals['_ERRORMESSAGE']._serialized_start=22
  _globals['_ERRORMESSAGE']._serialized_end=964
  _globals['_ERRORMESSAGE_CODE']._serialized_start=196
  _globals['_ERRORMESSAGE_CODE']._serialized_end=397
  _globals['_ERRORMESSAGE_TYPE']._serialized_start=400
  _globals['_ERRORMESSAGE_TYPE']._serialized_end=869
  _globals['_ERRORMESSAGE_SEVERITY']._serialized_start=871
  _globals['_ERRORMESSAGE_SEVERITY']._serialized_end=964
# @@protoc_insertion_point(module_scope)
