# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GambleData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'GambleData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Error_pb2 as Error__pb2
from . import PurchaseData_pb2 as PurchaseData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10GambleData.proto\x12\x04\x44\x61ta\x1a\x0b\x45rror.proto\x1a\x12PurchaseData.proto\"\xba\x01\n\x0eGambleResponse\x12\x30\n\x0fupdatedCurrency\x18\x01 \x01(\x0b\x32\x12.Data.CurrencyDataH\x00\x88\x01\x01\x12\x1c\n\x0f\x63urrencyAwarded\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12&\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x12.Data.ErrorMessageH\x02\x88\x01\x01\x42\x12\n\x10_updatedCurrencyB\x12\n\x10_currencyAwardedB\x08\n\x06_errorB\x16\n\x14\x63om.ea.simpsons.datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GambleData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.ea.simpsons.data'
  _globals['_GAMBLERESPONSE']._serialized_start=60
  _globals['_GAMBLERESPONSE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
