# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetFriendData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'GetFriendData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import LandData_pb2 as LandData__pb2
from . import Error_pb2 as Error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13GetFriendData.proto\x12\x04\x44\x61ta\x1a\x0eLandData.proto\x1a\x0b\x45rror.proto\"(\n\x14GetFriendDataRequest\x12\x10\n\x08\x66riendId\x18\x01 \x03(\t\"\xdf\x04\n\x15GetFriendDataResponse\x12>\n\nfriendData\x18\x01 \x03(\x0b\x32*.Data.GetFriendDataResponse.FriendDataPair\x12&\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.Data.ErrorMessageH\x00\x88\x01\x01\x1a\xd3\x03\n\x0e\x46riendDataPair\x12\x15\n\x08\x66riendId\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x35\n\nfriendData\x18\x02 \x01(\x0b\x32\x1c.Data.LandMessage.FriendDataH\x01\x88\x01\x01\x12N\n\x05\x65rror\x18\x03 \x01(\x0b\x32:.Data.GetFriendDataResponse.FriendDataPair.FriendDataErrorH\x02\x88\x01\x01\x12P\n\x0b\x61uthService\x18\x04 \x01(\x0e\x32\x36.Data.GetFriendDataResponse.FriendDataPair.AuthServiceH\x03\x88\x01\x01\x12\x17\n\nexternalId\x18\x05 \x01(\tH\x04\x88\x01\x01\x1aI\n\x0f\x46riendDataError\x12\x11\n\x04\x63ode\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04type\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_codeB\x07\n\x05_type\"(\n\x0b\x41uthService\x12\x0b\n\x07NUCLEUS\x10\x00\x12\x0c\n\x08\x46\x41\x43\x45\x42OOK\x10\x01\x42\x0b\n\t_friendIdB\r\n\x0b_friendDataB\x08\n\x06_errorB\x0e\n\x0c_authServiceB\r\n\x0b_externalIdB\x08\n\x06_errorB\x16\n\x14\x63om.ea.simpsons.datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFriendData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.ea.simpsons.data'
  _globals['_GETFRIENDDATAREQUEST']._serialized_start=58
  _globals['_GETFRIENDDATAREQUEST']._serialized_end=98
  _globals['_GETFRIENDDATARESPONSE']._serialized_start=101
  _globals['_GETFRIENDDATARESPONSE']._serialized_end=708
  _globals['_GETFRIENDDATARESPONSE_FRIENDDATAPAIR']._serialized_start=231
  _globals['_GETFRIENDDATARESPONSE_FRIENDDATAPAIR']._serialized_end=698
  _globals['_GETFRIENDDATARESPONSE_FRIENDDATAPAIR_FRIENDDATAERROR']._serialized_start=514
  _globals['_GETFRIENDDATARESPONSE_FRIENDDATAPAIR_FRIENDDATAERROR']._serialized_end=587
  _globals['_GETFRIENDDATARESPONSE_FRIENDDATAPAIR_AUTHSERVICE']._serialized_start=589
  _globals['_GETFRIENDDATARESPONSE_FRIENDDATAPAIR_AUTHSERVICE']._serialized_end=629
# @@protoc_insertion_point(module_scope)
